### ISSUE TITLE
Install and configure NelmioApiDocBundle with Swagger UI

### ISSUE THREAD

**Issue by voiteco** [voiteco/training-app-ai#22]
#### 📄 Description
Set up [NelmioApiDocBundle](https://symfony.com/bundles/NelmioApiDocBundle/current/index.html) to automatically generate and display Swagger UI documentation for the Symfony REST API. This will help developers understand and test API endpoints during development.

#### ⚙️ What to do

1. **Install NelmioApiDocBundle**

    ```bash
    composer require nelmio/api-doc-bundle
    ```

2. **Enable the bundle in `config/bundles.php`** (usually done automatically)

3. **Configure the bundle**

    Create or edit `config/packages/nelmio_api_doc.yaml`:

    ```yaml
    nelmio_api_doc:
        documentation:
            info:
                title: 'Training Booking API'
                description: 'API for training session booking system'
                version: '1.0.0'
        areas:
            default:
                path_patterns: [ '^/api' ]
    ```

4. **Add route for Swagger UI**

    In `config/routes/nelmio_api_doc.yaml`:

    ```yaml
    nelmio_api_doc:
        resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
        prefix: /api/docs
    ```

5. **Test the documentation**

    - Visit [http://localhost:8080/api/docs](http://localhost:8080/api/docs) in your browser
    - Ensure that your defined API routes appear automatically

6. **(Optional) Install OpenAPI annotations support**

    If you want to use PHPDoc annotations to describe routes:

    ```bash
    composer require zircote/swagger-php
    ```

#### ✅ Acceptance Criteria

- Swagger UI is available at `/api/docs`
- All `/api/*` routes are automatically documented
- API metadata (title, description, version) is shown correctly
- Developers can test API endpoints directly from the browser
