### ISSUE TITLE
Configure rate limiting for API

### ISSUE THREAD

**Issue by voiteco** [voiteco/training-app-ai#25]
#### 📄 Description
Protect the API from abuse or brute-force attacks by applying rate limiting using Symfony's built-in RateLimiter component. This ensures that users or devices cannot flood the backend with excessive requests.

#### ⚙️ What to do

1. **Install the RateLimiter component (if not installed)**

    ```bash
    composer require symfony/rate-limiter
    ```

2. **Configure default rate limiters**

    In `config/packages/rate_limiter.yaml`:

    ```yaml
    framework:
        rate_limiter:
            api_anonymous:
                policy: 'token_bucket'
                limit: 60
                rate: { interval: '1 minute', amount: 60 }
                cache_pool: 'cache.rate_limiter'
    ```

3. **Apply rate limiter to API routes using attributes**

    In controller methods:

    ```php
    use Symfony\Component\RateLimiter\RateLimiterFactory;
    use Symfony\Component\HttpKernel\Exception\TooManyRequestsHttpException;

    public function __construct(private RateLimiterFactory $apiLimiter) {}

    public function someApiAction(Request $request): JsonResponse
    {
        $limiter = $this->apiLimiter->create($request->getClientIp());
        $limit = $limiter->consume();

        if (!$limit->isAccepted()) {
            throw new TooManyRequestsHttpException('Rate limit exceeded.');
        }

        // Continue with logic
    }
    ```

4. **Optionally define custom limiters per route or group**

    - Example: more strict for booking endpoints

5. **Use cache pool for storage**

    - Redis will be used automatically if `framework.cache.pools` is configured with Redis for `cache.rate_limiter`

6. **Test by triggering more than allowed requests per minute**

#### ✅ Acceptance Criteria

- API returns `429 Too Many Requests` when rate limit is exceeded
- Rate limits are IP-based (or optionally `device_token`-based)
- Limiting logic does not interfere with normal traffic
- Rate limits are applied only to selected routes or the whole `/api/*` as needed
