### ISSUE TITLE
Configure dev proxy for API and enable CORS

### ISSUE THREAD

**Issue by voiteco** [voiteco/training-app-ai#4]
#### 📄 Description
Ensure the frontend (Vue + Vite) can communicate with the Symfony backend during local development by setting up a dev server proxy and enabling CORS on the backend.

This will prevent cross-origin issues when calling API endpoints from the frontend.

##### 1. **Configure Vite dev server proxy**
Edit `vite.config.js` and add the `server.proxy` section to forward API requests to the Symfony backend:

```js
export default defineConfig({
  // ...
  server: {
    proxy: {
      '/api': {
        target: 'http://localhost:8080', // Symfony backend via Nginx
        changeOrigin: true,
      }
    }
  }
})
```

##### 2. **Install and configure NelmioCorsBundle on Symfony**

```bash
composer require nelmio/cors-bundle
```

Then configure it in config/packages/nelmio_cors.yaml:

```yaml
nelmio_cors:
  defaults:
    allow_origin: ['http://localhost:5173']
    allow_methods: ['GET', 'POST', 'DELETE', 'OPTIONS']
    allow_headers: ['Content-Type', 'Authorization']
    max_age: 3600
  paths:
    '^/api/':
      allow_origin: ['http://localhost:5173']
      allow_headers: ['Content-Type', 'Authorization']
      allow_methods: ['GET', 'POST', 'DELETE', 'OPTIONS']
```

##### **3. Ensure OPTIONS requests are handled**

Symfony should allow OPTIONS requests to pass for CORS preflight. Verify with a simple fetch from frontend.

#### ✅ Acceptance Criteria

- Vue frontend can make requests to /api/... without CORS errors
- Proxy setup allows using relative paths (e.g., /api/trainings) in the frontend code
- All common HTTP methods (GET, POST, DELETE) work without preflight issues
